// Generated by CoffeeScript 1.7.1
(function() {
  var cluster, diameter, innerRadius, radius;

  diameter = 960;

  radius = diameter / 2;

  innerRadius = radius - 120;

  cluster = d2.layout.cluster().size([360, innerRadius]).sort(null).value(function(d) {
    return d.size;
  });

}).call(this);
